"""empty message

Revision ID: 3708c5727823
Revises: 598c96ee7dac
Create Date: 2023-06-21 17:32:31.041177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3708c5727823'
down_revision = '598c96ee7dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
