"""empty message

Revision ID: 54df3844d766
Revises: 3cc5133133ab
Create Date: 2023-06-22 15:53:58.081637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54df3844d766'
down_revision = '3cc5133133ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_table('order_items')
    # ### end Alembic commands ###
